### ISSUE TITLE
[Feature] Docker image documentation

### ISSUE THREAD

**Issue by Joly0** [MatteoFasulo/Whisper-TikTok#40]
Hey, you have written in your readme `However, there is also a Docker image available for Whisper-TikTok which can be used to run the program in a containerized environment.` so i am trying to set it up using docker, but there is no documentation and no docker image. It´s ok for me, i can build the image myself, but some documentation what paths, variables, etc are needed would be highly useful, otherwise i have to figure this out myself.

**Comment by MatteoFasulo** [comment]
Hi,
Docker image is available at https://github.com/MatteoFasulo/Whisper-TikTok/pkgs/container/whisper-tiktok (a cool feature of GitHub which allows to also upload docker images on repository). This image spins up the streamlit dashboard but due to the fact that the entire project requires Whisper model (and a lot of GPU related packages) it is a bit too heavy to run but still working.

**Comment by Joly0** [comment]
Hey, thanks for the quick reply. What about the documentation for the docker image? Could you maybe provide a quick docker run command?

**Comment by MatteoFasulo** [comment]
> Hey, thanks for the quick reply. What about the documentation for the docker image? Could you maybe provide a quick docker run command?

Hi, 
you can find a quick guid on how to use the image here: https://matteofasulo.github.io/Whisper-TikTok/3-docker/

**Comment by MatteoFasulo** [comment]
Did you manage to solve the issue @Joly0 ?

**Comment by Joly0** [comment]
Yep, works. Thx
